



 CREATE TABLE VENDEDORE
 (
    ID_empleado INT PRIMARY KEY IDENTITY NOT NULL,
	nomb1 VARCHAR (26),
	nomb2 VARCHAR (26),
	apell1 VARCHAR (26),
	apell2 VARCHAR (26),
    numcelu VARCHAR (8)NOT NULL,
	direc VARCHAR (30),
  )


<<<<<<< HEAD:BASE DATOS FINAL.sql
 
=======

  USE DB_MTE
>>>>>>> 4d2f5ee41e4433c8626e5acababde40e6352304a:basedata/BASE DATOS FINAL.sql
  CREATE TABLE CLIENTES 
 ( 
 
    codcli INT PRIMARY KEY NOT NULL,
	nomb1 VARCHAR (26),
	nomb2 VARCHAR (26),
	apell1 VARCHAR (26),
	apell2 VARCHAR (26),
	numcelu VARCHAR (8) NOT NULL,
	direc VARCHAR (30) ,
 )


 USE DB_MTE
  CREATE TABLE VENTAS
 ( 
    ID_venta INT PRIMARY KEY IDENTITY NOT NULL,
	fechaven DATETIME ,
	precio FLOAT,
	cant FLOAT ,
	codcli INT not null,
	ID_empleado INT not null
	CONSTRAINT fk_VENDEDORES FOREIGN KEY (ID_empleado) REFERENCES VENDEDORE (ID_empleado),
	CONSTRAINT fk_CLIENTES FOREIGN KEY (codcli) REFERENCES CLIENTES (codcli)
 )

 USE DB_MTE
CREATE TABLE PRODUCTO
(    
    ID_prod INT PRIMARY KEY IDENTITY NOT NULL,
	marca VARCHAR (26),
	modelo VARCHAR (26),
	garant DATETIME,
	orig  bit,
	descrip VARCHAR (100),
 )


 USE DB_MTE
 CREATE TABLE VENTAPRODUCTO
 (
    nrofactura INT PRIMARY KEY IDENTITY,
    fecha DATETIME,
	canti FLOAT ,
	monto FLOAT ,
	tipo_venta bit ,
	direc VARCHAR (30),
	ID_venta INT not null,
	ID_prod INT not null,
	CONSTRAINT fk_PRODUT FOREIGN KEY (ID_prod) REFERENCES PRODUCTO (ID_prod),
	CONSTRAINT fk_VENT FOREIGN KEY (ID_venta) REFERENCES VENTAS (ID_venta)
  )

   USE DB_MTE
  CREATE TABLE DEVOLUCIONES
 ( 
    ID_devoluciones INT PRIMARY KEY IDENTITY NOT NULL,
	descrip VARCHAR (100),
	fecha DATETIME ,
	ID_prod INT not null,
	CONSTRAINT fk_prod FOREIGN KEY (ID_prod) REFERENCES PRODUCTO (ID_prod),
  )



    USE DB_MTE
  CREATE TABLE PROVEEDORES
 ( 
    ruc VARCHAR (16) PRIMARY KEY NOT NULL,
	nomb VARCHAR (26),
	numcelu VARCHAR (8)NOT NULL,
	direc VARCHAR (30),
	ID_prod INT not null,
	CONSTRAINT fk_PRODUCTO FOREIGN KEY (ID_prod) REFERENCES PRODUCTO (ID_prod),
  )




